In [ ]:
#definição do problema
import numpy as np
#primeiro elemtento de cada entrada = bias = -1
entradas = np.array([ [-1,x,x,x], [-1,x,x,x], [-1,x,x,x], [-1,x,x,x], [-1,x,x,x] ])
print("as entradas são: \n", entradas)
saidas = np.array([ s, s, s, s, s])
print("as saidas são: \n", saidas)
pesos = np.array([x, x, x, x])
print("Os pesos são: \n", pesos)
taxaAprendizagem = 0.01
print("A taxa de aprendizagem é: \n", taxaAprendizagem)


as entradas são: 
 [[-1  0  1  1]
 [-1  1  1  1]
 [-1  1  0  1]
 [-1  1  1  0]
 [-1  0  0  0]]
as saidas são: 
 [-1 -1 -1  1  1]
Os pesos são: 
 [0.07 0.63 0.89 0.27]
A taxa de aprendizagem é: 
 0.01


In [11]:
def signfunction(soma):
    if ( soma >= 0 ):
        return 1
    else:
        return -1

In [22]:
def calculaSaida(inputs):   #multiplica as entradas pelos pesos, faz a soma e aplica função sinal
    s = np.dot(inputs,pesos) # dot faz multiplicão e soma das variaveis
    return signfunction(s)

In [23]:
i=4
s=np.dot(entradas[i], pesos)
x=signfunction(s)
print("a saida desejada era", saidas[i])
print("dot product", s)
print("saida obtida foi", x)
print("entrada",entradas[i])
print("pesos", pesos)
print("erro", abs(saidas[i] - x) )

a saida desejada era 1
dot product -0.07
saida obtida foi -1
entrada [-1  0  0  0]
pesos [0.07 0.63 0.89 0.27]
erro 2


In [26]:
def treinar():
    erroTotal = 1
    n=0
    while (erroTotal != 0):
        erroTotal = 0
        n=n+1
        print("epoch",n)
        for i in range(len(entradas)):
            saidaCalculada = calculaSaida(entradas[i])
            erro = saidas[i] - saidaCalculada
            if (erro != 0):
              erroTotal=erroTotal+1
              print("Errou na entrada", i)
            
            for j in range(len(pesos)):
                pesos[j] = pesos[j] + (taxaAprendizagem * entradas[i][j] * erro)
        print('Erros acumulados: ' + str(erroTotal))


In [28]:
i=4
print("i e igual a ", i)
print("entrada i", entradas[i])
print("saida para entrada i",saidas[i])
print("Previsão feita saida i", calculaSaida(entradas[i]))


i e igual a  4
entrada i [-1  0  0  0]
saida para entrada i 1
Previsão feita saida i -1


In [29]:
treinar()
print('Rede neural treinada')


epoch 1
Errou na entrada 0
Errou na entrada 1
Errou na entrada 2
Errou na entrada 4
Total de erros: 4
epoch 2
Errou na entrada 0
Errou na entrada 1
Errou na entrada 2
Errou na entrada 4
Total de erros: 4
epoch 3
Errou na entrada 0
Errou na entrada 1
Errou na entrada 2
Errou na entrada 4
Total de erros: 4
epoch 4
Errou na entrada 0
Errou na entrada 1
Errou na entrada 2
Errou na entrada 4
Total de erros: 4
epoch 5
Errou na entrada 0
Errou na entrada 1
Errou na entrada 2
Errou na entrada 4
Total de erros: 4
epoch 6
Errou na entrada 0
Errou na entrada 1
Errou na entrada 2
Errou na entrada 4
Total de erros: 4
epoch 7
Errou na entrada 0
Errou na entrada 1
Errou na entrada 4
Total de erros: 3
epoch 8
Errou na entrada 0
Errou na entrada 1
Errou na entrada 4
Total de erros: 3
epoch 9
Errou na entrada 0
Errou na entrada 1
Errou na entrada 4
Total de erros: 3
epoch 10
Errou na entrada 1
Errou na entrada 4
Total de erros: 2
epoch 11
Errou na entrada 1
Errou na entrada 4
Total de erros: 2
epoch 12


In [31]:
print("saida 1 calculada", calculaSaida(entradas[0]))
print("saida 1 Desejada", saidas[0])
print("saida 2 calculada",calculaSaida(entradas[1]))
print("saida 2 Desejada", saidas[1])
print("saida 3 calculada",calculaSaida(entradas[2]))
print("saida 3 Desejada", saidas[2])
print("saida 4 calculada",calculaSaida(entradas[3]))
print("saida 4 Desejada", saidas[3])
print("saida 5 calculada",calculaSaida(entradas[4]))
print("saida 5 Desejada", saidas[4])

saida 1 calculada -1
saida 1 Desejada -1
saida 2 calculada -1
saida 2 Desejada -1
saida 3 calculada -1
saida 3 Desejada -1
saida 4 calculada 1
saida 4 Desejada 1
saida 5 calculada 1
saida 5 Desejada 1


In [32]:
#Novas classes
entradas_novas = np.array([[-1, 0, 1, 0], [-1, 1, 0, 0], [-1, 0, 0, 1] ] )
#print(entradas_novas)
for i in range(len(entradas_novas)):
  saida = calculaSaida(entradas_novas[i])
  print(entradas_novas[i])
  if (saida==1):
    print("Entrada pertence  classe B \n")
  else:
    print("Entrada pertence  classe A \n")


[-1  0  1  0]
Entrada pertence  classe B 

[-1  1  0  0]
Entrada pertence  classe B 

[-1  0  0  1]
Entrada pertence  classe A 

